### ISSUE TITLE
Assignment 1-1 - The Basics

### ISSUE THREAD

**Issue by ambethia** [tlavon/assignments#1]
- [ ] Read Mason's [Code School Manefesto](http://masondesu.github.io/code-school-manifesto/).
- [ ] Look over this [Javascript Style Guide](https://github.com/airbnb/javascript/blob/master/README.md). You shouldn't to read it thoroughly. You won't understand all of it; that's okay. Just skim it, know that it exists, bookmark it, and refer to it often as we move forward. It's also not the only "one true way" to write code. Many organizations have their own style guides.
- [ ] Complete the just the six exercises given below by copying the comments to a new file  (`day_one.js`) and placing your solution below each comment.
- [ ] Publish your completed exercises to a Github Gist.
- [ ] Add a link to your gist to this Github Issue
- [ ] Close this issue to notify me for review.
- **Bonus**
  - [ ] Clone the Gist you created to your computer.
  - [ ] Add the bonus exercises (7 and 8) to your `day_one.js` and attempt to complete them both.
  - [ ] Push your changes (even if incomplete) back to Gist.
  - [ ] Spend some more time getting to know your terminal and text editor. Try finding some color schemes you like online and installing
  - [ ] Install `zsh` and `oh-my-zsh` and choose a theme of your liking. Take a screenshot of your terminal with the theme installed. Attach to the issue before closing. them. I like to match my editor and terminal colors.

`day_one.rb`:

``` js
// 1. Assign the message "Hello, World!" to a variable.

// 2. Assign a different string to a different variable.

// 3. Assign a number to a variable.

// 4. Use string concatenation to display the number from #3 in a string.

// 5. Make an array of at least four of your favorite movies or books or bands.

// 6. Make a object of information about yourself with at least four properties.
```
### Bonus Exercise

``` js
// 7. Make an array of objects containing more information about your favorite movies. The objects should have at least three properties.

// 8. Use `for` to loop through the answer from exercise #7 and print only one property from the object. i.e., given `{ title: "Gone with the Wind" }` you print "Gone with the Wind".
```

**Comment by tlavon** [comment]
https://gist.github.com/b168923cd165c0841aa0.git

**Comment by ambethia** [comment]
4,5,6 need a couple tweaks, we'll go over it in a homework review in the morning.

**Comment by tlavon** [comment]
Okay and I am working on the bonus problems now. I am stuck on #7 maybe because of how it was worded only because I thought arrays were for numbers and objects for strings so I am not 100% sure how to combine both.

**Comment by ambethia** [comment]
![Awesome Work!](http://s3.amazonaws.com/giphygifs/media/L8Tn9YmDPPQsM/200w_d.gif)
