### ISSUE TITLE
Assignment 7-2 - Getting Ready for React

### ISSUE THREAD

**Issue by ambethia** [tlavon/assignments#24]
# Getting Ready for React

This week we are going to throw React.js into the mix. React is a bit of a departure from how we've been thinking about "views" in our apps.

Here's a talk from JSConf by Pete Hunt (Instagram/Facebook) for you to watch. In addition, I want you to do some digging, Googling, etc. about React.

[![](http://img.youtube.com/vi/x7cQ3mrcKaY/0.jpg)](http://www.youtube.com/watch?v=x7cQ3mrcKaY)

Write a short blog post about your initial thoughts on React. Does it look daunting? Are you excited? Does it's almost 'philosophical' approach to solving problems appeal to you?

**Comment by tlavon** [comment]
https://medium.com/@neeshgee/reactjs-6a80a5a8bd93
